package com.test.springcloud.client.mapper;

import com.test.springcloud.client.entity.ZipkinSpans;

import java.util.List;

public interface ZipkinSpansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zipkin_spans
     *
     * @mbggenerated
     */
    int insert(ZipkinSpans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zipkin_spans
     *
     * @mbggenerated
     */
    List<ZipkinSpans> selectAll();
}