spring:
  application:
    name: config-client
  cloud:
    config:
      lable: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enable: true
        serviceId: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh