package com.test.springcloud.client.entity;

import java.io.Serializable;

public class ZipkinSpans implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.trace_id_high
     *
     * @mbggenerated
     */
    private Long traceIdHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.trace_id
     *
     * @mbggenerated
     */
    private Long traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.debug
     *
     * @mbggenerated
     */
    private Boolean debug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.start_ts
     *
     * @mbggenerated
     */
    private Long startTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zipkin_spans.duration
     *
     * @mbggenerated
     */
    private Long duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zipkin_spans
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.trace_id_high
     *
     * @return the value of zipkin_spans.trace_id_high
     *
     * @mbggenerated
     */
    public Long getTraceIdHigh() {
        return traceIdHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.trace_id_high
     *
     * @param traceIdHigh the value for zipkin_spans.trace_id_high
     *
     * @mbggenerated
     */
    public void setTraceIdHigh(Long traceIdHigh) {
        this.traceIdHigh = traceIdHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.trace_id
     *
     * @return the value of zipkin_spans.trace_id
     *
     * @mbggenerated
     */
    public Long getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.trace_id
     *
     * @param traceId the value for zipkin_spans.trace_id
     *
     * @mbggenerated
     */
    public void setTraceId(Long traceId) {
        this.traceId = traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.id
     *
     * @return the value of zipkin_spans.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.id
     *
     * @param id the value for zipkin_spans.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.name
     *
     * @return the value of zipkin_spans.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.name
     *
     * @param name the value for zipkin_spans.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.parent_id
     *
     * @return the value of zipkin_spans.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.parent_id
     *
     * @param parentId the value for zipkin_spans.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.debug
     *
     * @return the value of zipkin_spans.debug
     *
     * @mbggenerated
     */
    public Boolean getDebug() {
        return debug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.debug
     *
     * @param debug the value for zipkin_spans.debug
     *
     * @mbggenerated
     */
    public void setDebug(Boolean debug) {
        this.debug = debug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.start_ts
     *
     * @return the value of zipkin_spans.start_ts
     *
     * @mbggenerated
     */
    public Long getStartTs() {
        return startTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.start_ts
     *
     * @param startTs the value for zipkin_spans.start_ts
     *
     * @mbggenerated
     */
    public void setStartTs(Long startTs) {
        this.startTs = startTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zipkin_spans.duration
     *
     * @return the value of zipkin_spans.duration
     *
     * @mbggenerated
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zipkin_spans.duration
     *
     * @param duration the value for zipkin_spans.duration
     *
     * @mbggenerated
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zipkin_spans
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", traceIdHigh=").append(traceIdHigh);
        sb.append(", traceId=").append(traceId);
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", parentId=").append(parentId);
        sb.append(", debug=").append(debug);
        sb.append(", startTs=").append(startTs);
        sb.append(", duration=").append(duration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}