eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  #当前服务端口号
  port: 8764
spring:
  application:
    name: service-ribbon

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"